-- Portfolio admin backend (as generated by Lovable Cloud)
-- Reproduces the live schema: content tables + admin roles + claim_admin RPC + RLS.
-- Idempotent: safe to re-run on a project where it is already applied,
-- and ready to apply as-is on a fresh Supabase project.

-- ---------------------------------------------------------------------------
-- Enum
-- ---------------------------------------------------------------------------
do $$ begin
  create type public.app_role as enum ('admin', 'user');
exception
  when duplicate_object then null;
end $$;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null default '',
  image_url text,
  tags text[] not null default '{}',
  live_url text,
  repo_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.skills (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.education (
  id uuid primary key default gen_random_uuid(),
  institution text not null,
  program text not null default '',
  period text not null default '',
  description text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.app_role not null,
  created_at timestamptz not null default now(),
  unique (user_id, role)
);

-- keep updated_at fresh on update
create extension if not exists moddatetime with schema extensions;

do $$ begin
  create trigger set_updated_at before update on public.projects
    for each row execute function extensions.moddatetime(updated_at);
exception when duplicate_object then null; end $$;
do $$ begin
  create trigger set_updated_at before update on public.skills
    for each row execute function extensions.moddatetime(updated_at);
exception when duplicate_object then null; end $$;
do $$ begin
  create trigger set_updated_at before update on public.education
    for each row execute function extensions.moddatetime(updated_at);
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- Helper + claim functions (SECURITY DEFINER, fixed search_path)
-- ---------------------------------------------------------------------------
create or replace function public.has_role(_user_id uuid, _role public.app_role)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = _user_id and role = _role
  );
$$;

-- Grants the admin role to the caller ONLY while no admin exists yet.
create or replace function public.claim_admin()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  admin_exists boolean;
begin
  if auth.uid() is null then
    return false;
  end if;

  select exists (select 1 from public.user_roles where role = 'admin')
    into admin_exists;

  if admin_exists then
    return false;
  end if;

  insert into public.user_roles (user_id, role)
  values (auth.uid(), 'admin')
  on conflict (user_id, role) do nothing;

  return true;
end;
$$;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.projects   enable row level security;
alter table public.skills     enable row level security;
alter table public.education  enable row level security;
alter table public.user_roles enable row level security;

-- Public read for everyone (anon + authenticated)
drop policy if exists "Public read projects" on public.projects;
create policy "Public read projects" on public.projects
  for select using (true);

drop policy if exists "Public read skills" on public.skills;
create policy "Public read skills" on public.skills
  for select using (true);

drop policy if exists "Public read education" on public.education;
create policy "Public read education" on public.education
  for select using (true);

-- Writes only for admins
drop policy if exists "Admin insert projects" on public.projects;
create policy "Admin insert projects" on public.projects
  for insert to authenticated
  with check (public.has_role(auth.uid(), 'admin'));

drop policy if exists "Admin update projects" on public.projects;
create policy "Admin update projects" on public.projects
  for update to authenticated
  using (public.has_role(auth.uid(), 'admin'))
  with check (public.has_role(auth.uid(), 'admin'));

drop policy if exists "Admin delete projects" on public.projects;
create policy "Admin delete projects" on public.projects
  for delete to authenticated
  using (public.has_role(auth.uid(), 'admin'));

drop policy if exists "Admin insert skills" on public.skills;
create policy "Admin insert skills" on public.skills
  for insert to authenticated
  with check (public.has_role(auth.uid(), 'admin'));

drop policy if exists "Admin update skills" on public.skills;
create policy "Admin update skills" on public.skills
  for update to authenticated
  using (public.has_role(auth.uid(), 'admin'))
  with check (public.has_role(auth.uid(), 'admin'));

drop policy if exists "Admin delete skills" on public.skills;
create policy "Admin delete skills" on public.skills
  for delete to authenticated
  using (public.has_role(auth.uid(), 'admin'));

drop policy if exists "Admin insert education" on public.education;
create policy "Admin insert education" on public.education
  for insert to authenticated
  with check (public.has_role(auth.uid(), 'admin'));

drop policy if exists "Admin update education" on public.education;
create policy "Admin update education" on public.education
  for update to authenticated
  using (public.has_role(auth.uid(), 'admin'))
  with check (public.has_role(auth.uid(), 'admin'));

drop policy if exists "Admin delete education" on public.education;
create policy "Admin delete education" on public.education
  for delete to authenticated
  using (public.has_role(auth.uid(), 'admin'));

-- Roles are visible to signed-in users only (needed for has_role check in UI)
drop policy if exists "Authenticated read user_roles" on public.user_roles;
create policy "Authenticated read user_roles" on public.user_roles
  for select to authenticated
  using (true);

-- ---------------------------------------------------------------------------
-- Explicit grants
-- ---------------------------------------------------------------------------
grant select on public.projects, public.skills, public.education to anon, authenticated;
grant insert, update, delete on public.projects, public.skills, public.education to authenticated, service_role;
grant select on public.user_roles to authenticated;
grant all on public.user_roles to service_role;
